### ISSUE TITLE
Autocorrect destroys undo history

### ISSUE THREAD

**Issue by AndrewRayCode** [misogi/vscode-ruby-rubocop#48] opened 2017-05-08 22:37 UTC
1. Make changes to a file
2. Run autocorrect
3. Try to undo

Undo history is lost by using the autocorrect feature. This plugin is dangerous!

**Comment by damien** [comment] 2017-05-09 17:26
@AndrewRayCode For my own reference, could you give a more detailed accounting of your use-case? In particular:

* Are you running Rubocop via the command line or via Intellisense/VSCode (right click + fix all issues)?
* Are you autocorrecting a single file or multiple files in a project?
* What version of Rubocop and VSCode are you using?
* What version of the vscode-ruby-rubocop plugin are you using?

Thanks!

<hr>

As an aside, I'd strongly recommend using source control and committing your work immediately before running scripts that automatically change your code. It's not a fix for this bug, but it'll take the sting out of it and similar issues you may run into with other extensions/CLI tools.

**Comment by AndrewRayCode** [comment] 2017-05-09 19:01
I'm in a single file, hitting command-shift-P, and typing "autocorrect" and selecting "Rubocop > autocorrect", which as I understand is provided by this plugin

I'm using the latest version of this plugin as far as I know. No upgrade icon. Latest vscode. 

    rubocop --version
        0.47.1

I version control my files. That shouldn't be related to this. I'm not going to make a commit "pre-code-linting save place", which still won't solve the undo history problem. After writing brand new code, I want to auto-format it. Of course I want to keep undo history here because I've just written brand new code. No other plugins work like this, in vscode or any other editor, for example the JS "prettier" plugin or eslint plugin autofix feature keep undo history.

**Comment by damien** [comment] 2017-05-09 21:22
@AndrewRayCode It's a fair criticism, I'm just trying to understand the context and expectations.

Based on your feedback, inline autocorrecting clearly needs more work (undo example being a great example of a pain point). If other plugins are supporting undos, we probably can as well.

I'm currently busy adding Bundler support, but this seems like a great feature to pull in. Would you be interested in contributing a fix to your problem @AndrewRayCode? I'm not the maintainer, but I'd be surprised if @misogi turned down any willing contributors.

**Comment by misogi** [comment] 2017-05-09 23:30
Thanks for your report.

You are right. I edit a code and execute autocorrect. Then I can't undo(Cmd+Z). I reproduced same issue.
But I don't understand why breaking undo history.

@sergey-kintsel Can you please help us?

**Comment by sergey-kintsel** [comment] 2017-05-09 23:49
That's true, it can't be reverted ( at least for now). As I understand, this is because autocorrect changes the file directly using file system. At the moment I do not know how to make it better

**Comment by damien** [comment] 2017-05-10 00:20
@misogi @sergey-kintsel I did a bit of digging, the VSCode extension API seems have an abstraction for file changes, though I'm not certain off the top of my head how we'd integrate them. See:

* [TextEditor.edit](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditor.edit): Perform an edit on the document associated with this text editor
* [TextEditorEdit](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditorEdit): A complex edit that will be applied in one transaction on a TextEditor. This holds a description of the edits and if the edits are valid (i.e. no overlapping regions, document was not changed in the meantime, etc.) they can be applied on a document associated with a text editor.

Looks like we'd need to figure out how to get rubocop autocorrect output without altering the underlying files and convert them into changes VSCode could implement via the workspace. I'm hoping there's an easier way to get VSCode to recognize side-effecting changes, because that sounds like a bit of a PITA to implement. I'll update this thread if I can fine some examples of how other extensions handle this behavior.

**Comment by damien** [comment] 2017-05-10 00:24
Quick update: Looking at the ESLint extension, it seems they're using [DocumentFormattingEditProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentFormattingEditProvider) under the VSCode languages namespace to do this sort of thing. We should probably look in there for ways to wrap rubocop's autocorrect/formatting functionality.

**Comment by esalter** [comment] 2017-05-11 11:34
I'd like to second this, I stumbled on this while I was hacking in support for autocorrecting on save.  Losing undo history is a big deal.

**Comment by AndrewRayCode** [comment] 2017-05-15 18:42
The updated flow should not save the file ever. It should replace the contents (or selected contents) with the autocorrected text, and show the file as unsaved. This is also consistent with how other plugins work. I'm not sure how that will interact with saving a file, I agree that should be a config option.

**Comment by pauloschilling** [comment] 2017-05-22 02:20
Would be really great if we can achieve this! 👏 

Right now I'm trying to move from Atom to vscode, and this kind of feature is really something I want to keep. 

**[Glavin001/atom-beautify](https://github.com/Glavin001/atom-beautify) works exactly the way we want** by not saving the file, and allowing the undo operation. It also works when you want to autocorrect only the selected lines.

**Closed** 2018-01-13 00:10 UTC
